### ISSUE TITLE
Service provider name changed

### ISSUE THREAD

**Issue by tyson-nw** [Kladislav/laravel-chunk-upload#1]
The instructions claim that
`php artisan vendor:publish --provider="Kladislav\LaravelChunkUpload\Providers\ChunkUploadServiceProvider"`

But with the renaming the provider is actually.
`php artisan vendor:publish --provider="Kladislav\LaravelChunkUpload\ServiceProvider"`

**Comment by Kladislav** [comment]
@tyson-nw yes, you are right, i fix it soon
